# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SummarooApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SummarooApp
pod 'Firebase/Analytics'
pod 'Firebase/Auth'	
pod 'lottie-ios'

  target 'SummarooAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SummarooAppUITests' do
    # Pods for testing
  end

end
